### ISSUE TITLE
Using function ucwords that only works from php 5.5.16 onwards

### ISSUE THREAD

**Issue by GemmaCowton** [castlegateit/cgit-wp-security-tool#2]
Hi John,

In securtyTool.php line 151 you use the function ucwords with two parameters.

When installing the plugin on my wammp which runs php 5.5.12 I receive an error that the function should only have one parameter. This is because the function was updated in 5.5.16 to use two parameters.

This is a bug for php uses using slightly older PHP.

Can this be changed?

**Comment by GemmaCowton** [comment]
Additional comments:
For reference - This functions converts first character to upper-case.
http://php.net/manual/en/function.ucwords.php

**Comment by jonmoss** [comment]
This is true of other plugins as well, including f.ex cgit-breadcrumb - I don't think this is a bug, since 5.5.16 is available on all our hosting and keeping PHP up to date on development environments is an onerous but necessary task?

It might be nice to have PHP version requirement notices on our plugins though.

**Comment by ajreading** [comment]
I've updated this plugins README.md to indicate the requirements. We shouldn't need to support lower than PHP 5.5 anymore.
